### ISSUE TITLE
@return void when actually return is array

### ISSUE THREAD

**Issue by kaizokupuffball** [neild3r/vscode-php-docblocker#121]
So.. Weird problem. When I use this extension in my Laravel project I get this weird problem where it says `@return void` even when my method is `public function method() { return [ ]; } `

Also when returning a redirect response, the return value is set to void for some reason.
Can it be fixed?

**Comment by neild3r** [comment]
@kaizokupuffball the problem is that in order to deduce the return type for this we'd have to be parse the code in the entire function which we don't currently do. We only regex the signature to keep the package simple. 

Really with php7 having return types you should be able to declare them in your method signature so it seems a bit extreme to do something as complex as parsing the whole function with this in mind.

**Comment by kaizokupuffball** [comment]
I understand, thanks for replying. :)
