### ISSUE TITLE
Add @created_date tag to the comments

### ISSUE THREAD

**Issue by jitin-joseph** [neild3r/vscode-php-docblocker#145]
![image](https://user-images.githubusercontent.com/62872551/89647592-68729a80-d8db-11ea-9765-b6317ed1cd7a.png)
this is an example of created date in sublime text
add a tag for @created_date in comments. It should return the current date and time if possible

**Comment by smileBeda** [comment]
@jitin-joseph you can achieve that by using the following in your template:

```
"whatever": {
			"content": "@whatever ${CURRENT_YEAR}-${CURRENT_MONTH}-${CURRENT_DATE} ${CURRENT_HOUR}:${CURRENT_MINUTE}"
		},
```
`whatever` is the name of your tag

You can add this to `php-docblocker.propertyTemplate` or `php-docblocker.functionTemplate` or `php-docblocker.classTemplate`

Note that however your new custom tag will NOT be picked up by PHPDoc for example.
It would probably be better to use the `@since` tag which supports a Description, where you could insert the date as well.
